# -*- coding: utf-8 -*-
"""Dynamical Collision.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1foUJPAoLIIG3mtUllg-faHzfWs-85EaU
"""

import numpy as np
import matplotlib.pyplot as plt
import matplotlib.gridspec as gridspec
from matplotlib.lines import Line2D


plt.rcParams.update({
    'font.family': 'serif',
    'font.serif': ['Computer Modern Roman', 'Times New Roman', 'DejaVu Serif'],
    'mathtext.fontset': 'cm',
    'axes.labelsize': 10,
    'font.size': 10,
    'legend.fontsize': 7.5,
    'xtick.labelsize': 8,
    'ytick.labelsize': 8,
    'figure.dpi': 300
})


beta = 0.05
mu = 0.5
lambda_c = 0.01

def Z(p): return 1.0 / (1.0 + beta * p**2)
def dZ_dp(p): return -2.0 * beta * p / (1.0 + beta * p**2)**2
def V(p): return 0.5 * mu**2 * p**2 + 0.25 * lambda_c * p**4
def dV_dp(p): return mu**2 * p + lambda_c * p**3


N = 200
L = 10.0
dx = 2 * L / (N - 1)
x = np.linspace(-L, L, N)
y = np.linspace(-L, L, N)
z = np.linspace(-L, L, N)

X, Y, Z_grid = np.meshgrid(x, y, z, indexing='ij')


def compute_spatial_derivatives_4th(f, dx):
    """
    Calcule le gradient et le laplacien en différences finies d'ordre 4.
    Le padding 'edge' évite les artefacts de périodicité (wrap-around) aux bords.
    """
    fp = np.pad(f, 2, mode='edge')


    gx = (-fp[4:, 2:-2, 2:-2] + 8*fp[3:-1, 2:-2, 2:-2] - 8*fp[1:-3, 2:-2, 2:-2] + fp[:-4, 2:-2, 2:-2]) / (12*dx)
    gy = (-fp[2:-2, 4:, 2:-2] + 8*fp[2:-2, 3:-1, 2:-2] - 8*fp[2:-2, 1:-3, 2:-2] + fp[2:-2, :-4, 2:-2]) / (12*dx)
    gz = (-fp[2:-2, 2:-2, 4:] + 8*fp[2:-2, 2:-2, 3:-1] - 8*fp[2:-2, 2:-2, 1:-3] + fp[2:-2, 2:-2, :-4]) / (12*dx)


    lap = (
        -fp[4:, 2:-2, 2:-2] + 16*fp[3:-1, 2:-2, 2:-2] - 30*f + 16*fp[1:-3, 2:-2, 2:-2] - fp[:-4, 2:-2, 2:-2] +
        -fp[2:-2, 4:, 2:-2] + 16*fp[2:-2, 3:-1, 2:-2] - 30*f + 16*fp[2:-2, 1:-3, 2:-2] - fp[2:-2, :-4, 2:-2] +
        -fp[2:-2, 2:-2, 4:] + 16*fp[2:-2, 2:-2, 3:-1] - 30*f + 16*fp[2:-2, 2:-2, 1:-3] - fp[2:-2, 2:-2, :-4]
    ) / (12*dx**2)

    return gx, gy, gz, lap


print(f"Initializing 3D grid ({N}x{N}x{N})...")
R1 = np.sqrt((X - 2.0)**2 + Y**2 + Z_grid**2)
R2 = np.sqrt((X + 2.0)**2 + Y**2 + Z_grid**2)

p = 0.5 * np.exp(-R1**2 / 4.0) + 0.5 * np.exp(-R2**2 / 4.0)
Pi = np.zeros_like(p)


dt = 0.1 * dx
steps = 200
snapshots = []

def compute_derivatives(p, Pi):
    gx, gy, gz, lap_p = compute_spatial_derivatives_4th(p, dx)
    grad_p_sq = gx**2 + gy**2 + gz**2

    Z_val = Z(p)
    dZ_val = dZ_dp(p)
    dV_val = dV_dp(p)

    dt_p = Pi


    dt_Pi = lap_p + 0.5 * (dZ_val / Z_val) * (grad_p_sq - Pi**2) - (dV_val / Z_val)


    gPix, gPiy, gPiz = np.gradient(Pi, dx)


    dt_p[0, :, :] = gx[0, :, :]
    dt_p[-1, :, :] = -gx[-1, :, :]
    dt_Pi[0, :, :] = gPix[0, :, :]
    dt_Pi[-1, :, :] = -gPix[-1, :, :]


    dt_p[:, 0, :] = gy[:, 0, :]
    dt_p[:, -1, :] = -gy[:, -1, :]
    dt_Pi[:, 0, :] = gPiy[:, 0, :]
    dt_Pi[:, -1, :] = -gPiy[:, -1, :]


    dt_p[:, :, 0] = gz[:, :, 0]
    dt_p[:, :, -1] = -gz[:, :, -1]
    dt_Pi[:, :, 0] = gPiz[:, :, 0]
    dt_Pi[:, :, -1] = -gPiz[:, :, -1]

    return dt_p, dt_Pi

print("Running 4D evolution with 4th-order spatial accuracy and Sommerfeld boundaries...")

num_panels = 5
save_steps = np.linspace(0, steps - 1, num_panels, dtype=int)

for step in range(steps):
    if step in save_steps:
        gx, gy, gz, _ = compute_spatial_derivatives_4th(p, dx)
        snapshots.append((step * dt, p[:, :, N//2].copy(), gx[:, :, N//2].copy(), gy[:, :, N//2].copy()))


    k1_p, k1_Pi = compute_derivatives(p, Pi)
    k2_p, k2_Pi = compute_derivatives(p + 0.5*dt*k1_p, Pi + 0.5*dt*k1_Pi)
    k3_p, k3_Pi = compute_derivatives(p + 0.5*dt*k2_p, Pi + 0.5*dt*k2_Pi)
    k4_p, k4_Pi = compute_derivatives(p + dt*k3_p, Pi + dt*k3_Pi)

    p  += (dt / 6.0) * (k1_p + 2*k2_p + 2*k3_p + k4_p)
    Pi += (dt / 6.0) * (k1_Pi + 2*k2_Pi + 2*k3_Pi + k4_Pi)


X_2d, Y_2d = np.meshgrid(x, y)

fig = plt.figure(figsize=(7.5, 2.8))
fig.suptitle("Dynamical Collision of Scalar Solitons ($z=0$)", fontsize=12, fontweight='bold', y=0.98)


fig.subplots_adjust(top=0.82, bottom=0.25, left=0.06, right=0.92, wspace=0.08)
gs = gridspec.GridSpec(1, len(snapshots) + 1, width_ratios=[1]*len(snapshots) + [0.03])

vmin, vmax = 0, 1.2
cmap = 'magma'
step_q = 12

for i, (time, slice_2d, gx, gy) in enumerate(snapshots):
    ax = fig.add_subplot(gs[0, i])


    im = ax.imshow(slice_2d.T, origin='lower', extent=[-L, L, -L, L],
                   cmap=cmap, vmin=vmin, vmax=vmax, interpolation='bicubic')


    ax.contour(X_2d, Y_2d, slice_2d.T, levels=6, colors='white', alpha=0.4, linewidths=0.6, linestyles='solid')


    ax.quiver(X_2d[::step_q, ::step_q], Y_2d[::step_q, ::step_q],
              gx.T[::step_q, ::step_q], gy.T[::step_q, ::step_q],
              color='cyan', alpha=0.7, scale=4, width=0.005, headwidth=4)


    ax.set_title(f"$t = {time:.2f}$", fontsize=9.5, pad=5)
    ax.set_xlabel("$x$", fontsize=10, labelpad=3)
    ax.set_xticks([-5, 0, 5])
    ax.tick_params(axis='both', direction='in', color='white', length=3.5)

    if i == 0:
        ax.set_ylabel("$y$", fontsize=10, labelpad=3)
        ax.set_yticks([-5, 0, 5])
    else:
        ax.set_yticks([])

    for spine in ax.spines.values():
        spine.set_edgecolor('black')
        spine.set_linewidth(0.8)


    text_kwargs = dict(color='white', ha='center', fontsize=8, alpha=1.0, weight='bold')
    if i == 0:
        ax.text(0, -8.2, "Initial Blobs", **text_kwargs)
    elif i == 2:
        ax.text(0, -8.2, "Merger Phase", **text_kwargs)
    elif i == 4:
        ax.text(0, -8.2, "Oscillation Phase", **text_kwargs)


cbar_ax = fig.add_subplot(gs[0, -1])
cbar = fig.colorbar(im, cax=cbar_ax)
cbar.set_label("Amplitude $p(x,y)$", fontsize=9.5, rotation=270, labelpad=14)
cbar.ax.tick_params(labelsize=8, direction='in')
cbar.outline.set_linewidth(0.8)


legend_elements = [
    Line2D([0], [0], color='white', lw=1, alpha=0.6, label='Iso-amplitude contours'),
    Line2D([0], [0], marker=r'$\rightarrow$', color='cyan', label=r'Kinetic Gradient $\nabla p$',
           markerfacecolor='cyan', markersize=12, lw=0)
]
fig.legend(handles=legend_elements, loc='lower center', ncol=2, frameon=False,
           bbox_to_anchor=(0.48, 0.02), fontsize=9)

# plt.savefig("soliton_collision_enhanced.pdf", format='pdf', bbox_inches='tight', dpi=300)
plt.show()